config/routes.rb
JimmyCuadra::Application.routes.draw do
  # default route
  root to: "posts#index"

  # restful routes
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  get "comments/preview" => "comments#preview", as: :preview

  resources :tags, only: [:index, :show]

  # static pages
  get "/projects" => "pages#projects", as: :projects
  get "/resume" => "pages#resume", as: :resume
  get "/about" => redirect("/resume")

  # sessions
  get "/login" => "sessions#new", as: :new_login
  post "/login" => "sessions#create", as: :login
  get "/logout" => "sessions#destroy", as: :logout

  # legacy routes
  get "screencasts/1-*seo" => redirect("/posts/screencast-equalizing-column-heights-with-jquery")
  get "screencasts/2-*seo" => redirect("/posts/screencast-actionmailer-and-gmail")
  get "screencasts/3-*seo" => redirect("/posts/screencast-default-form-values-with-jquery")

  get "blog/1-*seo"  => redirect("/posts/big-update-new-blog-and-more")
  get "blog/2-*seo"  => redirect("/posts/frameworks-do-they-speed-things-up-or-slow-things-down")
  get "blog/3-*seo"  => redirect("/posts/twilight-site-launched")
  get "blog/4-*seo"  => redirect("/posts/kalenabovellcom-launched")
  get "blog/5-*seo"  => redirect("/posts/moxiemaster-application-under-development")
  get "blog/6-*seo"  => redirect("/posts/secure-authentication-with-javascript")
  get "blog/7-*seo"  => redirect("/posts/adventures-into-ruby-and-rails")
  get "blog/8-*seo"  => redirect("/posts/the-html-5-buzz-why-it-matters")
  get "blog/9-*seo"  => redirect("/posts/jimmy-cuadra-on-rails")
  get "blog/10-*seo" => redirect("/posts/from-cake-to-rails")
  get "blog/11-*seo" => redirect("/posts/can-google-chrome-frame-really-help")
  get "blog/12-*seo" => redirect("/posts/css3-transitions-and-animation-presentation-or-behavior")
  get "blog/13-*seo" => redirect("/posts/jimmy-cuadra-featured-on-html5-gallery")
  get "blog/14-*seo" => redirect("/posts/what-it-do-what-it-do")
  get "blog/15-*seo" => redirect("/posts/organizing-javascript-with-namespaces-and-function-prototypes")
  get "blog/16-*seo" => redirect("/posts/understanding-jquery-14s-proxy-method")
  get "blog/17-*seo" => redirect("/posts/do-websites-need-to-look-the-same-in-every-browser")
  get "blog/18-*seo" => redirect("/posts/checking-for-one-key-among-several-in-a-ruby-hash")
  get "blog/19-*seo" => redirect("/posts/javascript-factory-constructors")
  get "blog/20-*seo" => redirect("/posts/a-t-shirt-idea")
  get "blog/21-*seo" => redirect("/posts/keeping-track-of-javascript-event-handlers")
  get "blog/22-*seo" => redirect("/posts/metaprogramming-ruby-class-eval-and-instance-eval")
  get "blog/23-*seo" => redirect("/posts/project-roadmap")
  get "blog/24-*seo" => redirect("/posts/githubs-inflexible-pricing-model")
  get "blog/25-*seo" => redirect("/posts/to-lang-a-ruby-library-for-translating-strings")
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :name, :email, :comment
  validates_format_of :email, with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}\z/, allow_blank: true, message: "must be a valid email address"

  belongs_to :post

  before_save :prepend_scheme, unless: lambda { |record| record.url.blank? || record.url =~ /^https?:\/\// }
  after_create lambda { |comment| Notification.new_comment(comment).deliver unless comment.email == ENV['ADMIN_EMAIL'] }

  def admin!
    self.name = "Jimmy Cuadra"
    self.email = "jimmy@jimmycuadra.com"
    self.url = "http://jimmycuadra.com/"
  end

  private

  def prepend_scheme
    self.url = "http://#{url}"
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title, :body

  has_many :comments, dependent: :destroy

  extend FriendlyId
  friendly_id :title, use: :slugged
  acts_as_taggable

  after_validation :enforce_screencast_title, if: lambda { |record| record.screencast? }
  after_validation :enforce_screencast_tag, if: lambda { |record| record.screencast? }

  def screencast?
    !youtube_id.blank?
  end

  def comments_allowed?
    self.created_at > 2.weeks.ago
  end

  def normalize_friendly_id(text)
    text = "Screencast: #{text}" if screencast? && !title.starts_with?("Screencast: ")
    text.gsub!("_", "-")
    super
  end

  private

  def enforce_screencast_title
    self.title = "Screencast: #{title}" unless title.starts_with? "Screencast: "
  end

  def enforce_screencast_tag
    self.tag_list << "screencast" unless self.tag_list.include? "screencast"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :admin?

  def admin?
    session[:admin] == true
  end

  private

  def require_admin
    redirect_to root_path, notice: "You are not authorized." unless admin?
  end

  def require_no_admin
    redirect_to root_path, notice: "You are already logged in." if admin?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :require_admin, only: :destroy

  def create
    @post = Post.friendly.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.admin! if admin?
    if @comment.save
      redirect_to @post, notice: "Thanks for your comment!"
    else
      render 'posts/show', layout: 'application'
    end
  end

  def destroy
    @post = Post.friendly.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @post, notice: "The comment was destroyed."
  end

  def preview
    render inline: JimmyCuadra::Markdown.render(params[:comment], safe: true)
  end

  private

  def comment_params
    params[:comment] && params[:comment].permit(%i{name email url comment})
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_admin, except: [:index, :show]
  before_filter :retrieve_record, only: [:show, :update, :destroy]
  before_filter :enforce_friendly_url, only: :show

  def index
    @posts = Post.all
    @posts = @posts.where(published: true) unless admin?
    @posts = @posts.order('created_at desc')

    respond_to do |format|
      format.html { @posts = @posts.paginate(page: params[:page], per_page: 3) }
      format.atom { @posts = @posts.limit(10) }
    end
  end

  def show
  end

  def new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: "The post was created."
    else
      render :new
    end
  end

  def edit
    @post = Post.friendly.find(params[:id])
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to @post, notice: "The post was updated."
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "The post was destroyed."
  end

  private

  def post_params
    params[:post] && params[:post].permit(
      %i{title body youtube_id tag_list published}
    )
  end

  def retrieve_record
    posts = if admin?
      Post.all
    else
      Post.where(published: true)
    end
    @post = posts.friendly.find(params[:id])
  end

  def enforce_friendly_url
    redirect_to @post, status: :moved_permanently unless params[:id] == @post.friendly_id
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_no_admin, only: [:new, :create]

  def new
  end

  def create
    if password_match?(params[:password])
      session[:admin] = true
      redirect_to root_path, notice: "You are now logged in."
    else
      flash.now[:notice] = "Invalid password."
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: "You are now logged out."
  end

  private

  def password_match?(password)
    password == ENV['ADMIN_PASSWORD']
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.order("name asc")
  end

  def show
    begin
      @tag = ActsAsTaggableOn::Tag.friendly.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      return redirect_to tags_path, notice: "That tag was not found. The full list of tags is displayed below."
    end

    redirect_to tag_path(@tag), status: :moved_permanently unless params[:id] == @tag.friendly_id
    @posts = Post.tagged_with(@tag.name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_for(name, path, options = {})
    link_to_unless_current(name, path, options) do
      content_tag(:span) { name }
    end
  end

  def markdown(text, options = {})
    JimmyCuadra::Markdown.render(text, options)
  end
end

app/views/about/index.html.erb
<% @page_title = "About" %>
<div id="about">
  <h1>About me</h1>

  <figure>
    <img src="/assets/about/jimmy.jpg" width="256" height="256" alt="Jimmy Cuadra" />
  </figure>

  <p>I'm Jimmy Cuadra, a web developer from <a href="http://en.wikipedia.org/wiki/San_Diego">San Diego, California</a>. I grew up in <a href="http://en.wikipedia.org/wiki/Los_Angeles">Los Angeles</a>, and moved to San Diego in 2003 to attend <a href="http://ucsd.edu/">UCSD</a>, where I studied music technology and computer science. I graduated with a Bachelor's in Music with an emphasis in technology in 2008.</p>

  <p>I've worked with just about every part of the web stack, but primarily on the front end. I have experience working with HTML (and HTML5), CSS (including CSS 3), and JavaScript. In 2009, I started working with <a href="http://www.ruby-lang.org/">Ruby</a> and <a href="http://rubyonrails.org/">Ruby on Rails</a>, and have been really enjoying it. I have command line proficiency on UNIX systems and I'm a big fan of <a href="http://git-scm.com/">Git</a> for version control.</p>

  <p>I am currently working full time, but open to opportunities with companies using Ruby and JavaScript in San Diego or San Francisco.</p>

  <h2>Get in touch</h2>

  <ul>
    <li>Email: my first name at this domain</li>
    <li>Twitter: <a href="http://twitter.com/jimmycuadra">@jimmycuadra</a></li>
    <li>GitHub: <a href="https://github.com/jimmycuadra">jimmycuadra</a></li>
		<li>LinkedIn: <a href="http://www.linkedin.com/in/jimmycuadra">Jimmy Cuadra</a></li>
    <li>AIM: JimmyCuadraWeb</li>
  </ul>
</div>

app/views/application/_production_scripts.html.haml
%script{ src: "https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" }
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5500916-1']);
  _gaq.push(['_trackPageview']);
  _gaq.push(['_trackPageLoadTime']);
  (function(d, t) {
    var e = d.createElement(t), s = d.getElementsByTagName(t)[0];
    e.type = 'text/javascript'; e.async = true; e.src = 'http://www.google-analytics.com/ga.js';
    s.parentNode.insertBefore(e, s);
  })(document, 'script');

app/views/application/_site_footer.html.haml
%footer.site-footer
  .bucket
    %p= if admin?; link_to "Log out", logout_path, title: "Log out"; else; link_to "Log in", new_login_path, title: "Log in"; end
    %p Built on a <a href="http://www.apple.com/" title="Apple">Mac</a> using <a href="http://rubyonrails.org/" title="Ruby on Rails">Ruby on Rails</a>. Logo by <a href="http://stephanielucido.com/" title="Stephanie Lucido">Stephanie Lucido</a>. If you're not using <a href="http://www.google.com/chrome" title="Google Chrome">a Webkit browser</a>, get on that.
    %small
      &copy; #{Date.today.year.to_s} Jimmy Cuadra. All rights reserved.

app/views/application/_site_header.html.haml
%header.site-header
  .bucket
    %a.title-link{ href: "/", title: "Jimmy Cuadra" }
      = image_tag "logo.png", width: "75", height: "75", alt: "Jimmy Cuadra", class: "logo"
      %hgroup
        %h1.main-title I'm Jimmy Cuadra.
        %p I write about programming and open source software.
      .clear

%nav
  .bucket
    %ul
      %li= nav_for "Writing", root_path, title: "Writing"
      %li= nav_for "by tags", tags_path, class: "sub-nav", title: "Writing by tags"
      %li= nav_for "Résumé", resume_path, title: "Jimmy Cuadra's Résumé"
      %li= nav_for "Projects", projects_path, title: "Projects"
      - if admin?
        %li= nav_for "[ New post ]", new_post_path, title: "Create a new post"

app/views/application/_social_scripts.html.haml
:javascript
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/platform.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
  (function(d, t) {
    var e = d.createElement(t), s = d.getElementsByTagName(t)[0];
    e.type = 'text/javascript'; e.async = true; e.src = '//platform.twitter.com/widgets.js';
    s.parentNode.insertBefore(e, s);
  })(document, 'script');

app/views/comments/_comment.html.haml
%section.comment{ itemprop: "comment", itemscope: true, itemtype: "http://schema.org/UserComments" }
  %header.inner
    - if admin?
      = link_to "Delete comment", post_comment_path(comment.post, comment), method: "delete", confirm: "Are you sure you want to delete this comment?", class: "delete"
    %img{ src: "http://gravatar.com/avatar/#{Digest::MD5.hexdigest comment.email.downcase}.png?s=48", width: "48", height: "48", alt: "#{comment.name}" }
    %span{ itemprop: "creator" }
      = comment.url.blank? ? comment.name : link_to(comment.name, comment.url)
    commented
    %br
    %data{ itemprop: "commentTime", value: "#{comment.created_at.strftime "%Y-%m-%d"}" }
      = comment.created_at.strftime "%B %d, %Y"
    .clear
  %section.inner.comment-body{ itemprop: "commentText" }= markdown comment.comment, safe: true

app/views/comments/_form.html.haml
= semantic_form_for [@post, @comment || Comment.new] do |f|
  = f.inputs do
    - unless admin?
      = f.input :name
      = f.input :email, hint: "Your email address is only used for Gravatar. It will never be published, sold, or traded, and you will never receive unsolicited email."
      = f.input :url, label: "URL"
    = f.input :comment
  = f.actions do
    %li#comment_preview_action.action.input_action
      = f.button "Preview comment", name: "preview", id: "preview-comment", type: nil
    = f.action :submit, label: "Add comment"

#comment-preview-frame.hidden
  %h2 Comment Preview
  .preview-content

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      = "#{@page_title} | " if @page_title.present?
      = "Page #{params[:page]} | " if params[:page]
      Jimmy Cuadra
    = stylesheet_link_tag "application"
    = csrf_meta_tags
    %link{ rel: "alternate", type: "application/rss+xml", title: "RSS", href: "http://feeds.feedburner.com/jimmycuadra" }
    = render "production_scripts" if Rails.env.production?
  %body
    = render "site_header"
    .content
      .bucket
        - if flash[:notice]
          %section#flash.notice
            = flash[:notice]
        = yield
    = render "site_footer"
    = javascript_include_tag "jquery.min" unless Rails.env.production?
    = javascript_include_tag "application"
    = render "social_scripts" if Rails.env.production? || params[:social]

app/views/notification/new_comment.html.erb
Post: <%= link_to @comment.post.title, post_url(@comment.post, host: "jimmycuadra.com") %><br />
Author: <%= link_to @comment.name, "mailto:#{@comment.email}" %><br />
<br />
<%= @comment.comment %>

app/views/notification/new_comment.text.erb
Post: <%= @comment.post.title %> (<%= post_url(@comment.post, host: "jimmycuadra.com") %>)
Author: <%= @comment.name %> (<%= @comment.email %>)

<%= @comment.comment %>

app/views/pages/about.html.haml
- @page_title = "About"
.about{ itemscope: true, itemtype: "http://schema.org/Person" }
  %h1.headline About Jimmy Cuadra
  %figure
    %img{ src: "/assets/resume/to_lang.jpg", width: "256", height: "256", alt: "Jimmy Cuadra giving a presentation on his Ruby gem, to_lang, at a San Diego Ruby meeting", itemprop: "image" }

  %h2 Purpose

  %p To work for a company whose products or services influence social change. To focus on user experience and exceptional quality. To use Ruby, JavaScript/CoffeeScript, Git, and any form of test-first development.

  %h2 Skills

  %ul
    %li Programming languages: Ruby, JavaScript (including Node.js), CoffeeScript, Perl, PHP
    %li Major frameworks/libraries: Ruby on Rails, Sinatra, jQuery, Backbone, Underscore
    %li Version control with Git (and GitHub), Subversion
    %li Front end languages: HTML5, CSS 3, Haml, Sass/SCSS, JavaScript templating
    %li Collaboration on open source software
    %li Test-driven development, behavior-driven development, continuous integration (Test::Unit, RSpec, Guard, Travis)
    %li Command line proficiency (primarily Mac OS X, some Linux)
    %li Facebook app development (both Canvas and Connect)
    %li Mobile website development

  %h2 Qualifications

  %ul
    %li Excellent writing and communication skills
    %li Highly motivated
    %li Enjoys working with a team
    %li Interested in learning new technologies and using the best tool for the job
    %li Active in the local Ruby and JavaScript communities

  %h2 Work History

  %ul
    %li Eventful (2009 &mdash; present): Senior Front End Engineer
    %li Einstein Industries (2009): Production Engineer
    %li Miva Merchant (2009): Web Developer
    %li Rady School of Management (2007-2008): Web Developer

  %h2 Education

  %p Bachelor of Art in Music, with an emphasis in technology, University of California, San Diego (2008)

  %h2 References

  %p Available upon request.

  %h2 Contact
  %ul
    %li Email: <span itemprop="email">my first name at this domain</span>
    %li Twitter: <a href="http://twitter.com/jimmycuadra">@jimmycuadra</a>
    %li GitHub: <a href="https://github.com/jimmycuadra">jimmycuadra</a>
    %li LinkedIn: <a href="http://www.linkedin.com/in/jimmycuadra">Jimmy Cuadra</a>
    %li AIM: JimmyCuadraWeb

app/views/pages/projects.html.haml
- @page_title = "Projects"
.projects
  %section
    %hgroup
      %h1 Projects
      %span Highlighted software I've created or helped develop. All my open source projects are available on <a href="https://github.com/jimmycuadra">GitHub</a>.
    %ul
      %li
        %figure
          %a{ href: "http://jimmycuadra.github.io/lita/", title: "Lita" }
            %img{ src: "http://f.cl.ly/items/0c271a2P3k2V180B1R0X/lita.jpg", width: "184", height: "184", alt: "Lita" }
        %h2
          %a{ href: "http://jimmycuadra.github.io/lita/", title: "Lita" } Lita
        %p <strong>Lita</strong> is a chat bot written in Ruby with persistent storage provided by <a href="http://redis.io/">Redis</a>. It can connect to any chat service and can have new behavior added via handler plugins. The plugin system is managed with regular RubyGems and Bundler.
        %p Lita was featured in <a href="http://rubyweekly.com/archive/153.html">Ruby Weekly, Issue 153</a> on July 11, 2013, and on <a href="http://www.rubyinside.com/this-month-in-ruby-peepcode-acquired-a-free-rails-4-0-book-rails-3-2-14-and-more-6156.html">Ruby Inside</a> on July 25, 2013.
        .clear
      %li
        %figure
          %a{ href: "https://github.com/jimmycuadra/pushing-hands", title: "Pushing Hands" }
            = image_tag "projects/pushing_hands.jpg", width: 359, height: 196, alt: "Pushing Hands"
        %h2
          %a{ href: "https://github.com/jimmycuadra/pushing-hands", title: "Pushing Hands" } Pushing Hands
        %p <strong>Pushing Hands</strong> is a web-based game built for the <a href="https://github.com/blog/1303-github-game-off">GitHub Game Off</a>. It was built with Backbone.js, jQuery, Haml, Sass, Twitter Bootstrap, and Middleman.
        .clear
      %li
        %figure
          %a{ href: "http://morethingsneed.to/", title: "More Things Need To" }
            = image_tag "projects/mtnt.jpg", width: "238", height: "170", alt: "More Things Need To"
        %h2
          %a{ href: "http://morethingsneed.to/", title: "More Things Need To" } More Things Need To
        %p
          <strong>More Things Need To</strong> records humorous Mad Lib-style sentences, based on a long-running joke between my friend and me. It allows users to browse the collection, discuss and vote on their favorites, and submit their own entries. Built with Ruby on Rails.
        .clear
      %li
        %h2
          %a{ href: "https://github.com/jimmycuadra/to_lang", title: "to_lang" } to_lang
        %p
          <strong>to_lang</strong> is a Ruby library that adds language translation methods to the String and Array classes. It was featured on the <a href="http://ruby5.envylabs.com/episodes/141-episode-138-january-4-2011/stories/1229-to_lang-a-ruby-interface-to-google-translate">Ruby5 podcast</a> on January 4, 2011 and on <a href="http://news.ycombinator.com/item?id=2095006">Hacker News</a> on January 11, 2011.

      %li
        %h2
          %a{ href: "https://github.com/jimmycuadra/jimmycuadra.com", title: "jimmycuadra.com" } jimmycuadra.com
        %p
          My professional blog and résumé, built with Ruby on Rails and open sourced to demonstrate my programming ability and style.
      %li
        %h2
          %a{ href: "https://github.com/jimmycuadra/bang", title: "Bang" } Bang
        %p
          <strong>Bang</strong> is a command line program for storing and retrieving text snippets. Built with CoffeeScript, Jasmine, and Node.js.

app/views/pages/resume.html.haml
- @page_title = "Résumé"
.about{ itemscope: true, itemtype: "http://schema.org/Person" }
  %h1.headline Jimmy Cuadra's Résumé
  %figure
    = image_tag "resume/to_lang.jpg", width: "256", height: "256", alt: "Jimmy Cuadra giving a presentation on his Ruby gem, to_lang, at a San Diego Ruby meeting", itemprop: "image"

  %h2 Skills

  %ul
    %li Expert level programming in Ruby, JavaScript, and CoffeeScript
    %li Expert level knowledge of Ruby on Rails
    %li Excellent understanding of Python, Shell (Bash), and Perl
    %li Front end technologies: HTML, CSS, Haml, Sass, jQuery, Backbone, Underscore, and JavaScript templating
    %li Version control with Git, GitHub, and Subversion
    %li Test-driven development in multiple languages, test automation, and continuous integration
    %li Virtual machines and containers with Vagrant, VirtualBox, VMware Fusion, and Docker
    %li Configuration and deployment of applications to Heroku, Amazon Web Services, and DigitalOcean
    %li Devops with Chef, Puppet, Ansible, Hubot, and my own chat bot, <a http://jimmycuadra.github.io/lita/>Lita</a>
    %li Command line proficiency (primarily Mac OS X, some Ubuntu and CentOS)

  %h2 Personal Qualities

  %ul
    %li Excellent writing skills
    %li Highly motivated and passionate about good software engineering
    %li Self-directed and self-managing
    %li Interested in learning new technologies
    %li Active in the open source software community

  %h2 Work History

  %ul
    %li InQuicker (2014 &mdash; present): Senior Developer
    %li Uber (2013 &mdash; 2014): Software Engineer
    %li Change.org (2012 &mdash; 2013): Software Engineer
    %li Eventful (2009 &mdash; 2012): Senior Front End Engineer
    %li Einstein Industries (2009): Production Engineer
    %li Miva Merchant (2009): Web Developer
    %li Rady School of Management (2007-2008): Web Developer

  %h2 Education

  %p Bachelor's degree, University of California, San Diego

  %h2 References

  %p Available upon request.

  %h2 Contact
  %ul
    %li Email: <span itemprop="email">my first name at this domain</span>
    %li Twitter: <a href="http://twitter.com/jimmycuadra">@jimmycuadra</a>
    %li GitHub: <a href="https://github.com/jimmycuadra">jimmycuadra</a>

app/views/partials/_social_scripts.html.erb
<script type="text/javascript">
  (function(d, t) {
    var e = d.createElement(t), s = d.getElementsByTagName(t)[0];
    e.type = 'text/javascript'; e.async = true; e.src = 'https://apis.google.com/js/plusone.js';
    s.parentNode.insertBefore(e, s);
  })(document, 'script');
  (function(d, t) {
    var e = d.createElement(t), s = d.getElementsByTagName(t)[0];
    e.type = 'text/javascript'; e.async = true; e.src = 'https://platform.twitter.com/widgets.js';
    s.parentNode.insertBefore(e, s);
  })(document, 'script');
</script>

app/views/posts/_form.html.haml
= semantic_form_for @post || Post.new do |f|
  = f.inputs do
    = f.input :title
    = f.input :body
    = f.input :tag_list, label: "Tags"
    = f.input :youtube_id, label: "YouTube ID"
    = f.input :published, label: "Publish"
  = f.actions

app/views/posts/_post.html.haml
%article{ itemscope: true, itemtype: "http://schema.org/BlogPosting" }
  %meta{ itemprop: "author", content: "Jimmy Cuadra" }
  %header
    %h1.post-title{ itemprop: "headline" }= link_to_unless_current post.title, post, title: post.title
    %data{ itemprop: "datePublished", value: post.created_at.strftime("%Y-%m-%d") }= post.created_at.strftime("%B %d, %Y")
    - if admin?
      \ -
      = link_to "Edit post", [:edit, post]
      \ -
      = link_to "Delete post", post, method: :delete, data: { confirm: "Are you sure you want to delete this post?" }
  .social
    .g-plus{ data: { action: "share", annotation: "bubble", href: post_url(post) } }
    %a.twitter-share-button{ href: "https://twitter.com/share", data: { url: post_url(post), text: post.title, count: "horizontal", via: "jimmycuadra" } } Tweet
  - unless post.published
    .unpublished This post is currently unpublished.
  - if post.youtube_id.present? && params[:action] == "show"
    %object{ width: "640", height: "385", itemprop: "video", itemscope: true, itemtype: "http://schema.org/VideoObject" }
      %meta{ itemprop: "embedURL", content: "http://www.youtube.com/v/#{post.youtube_id}?fs=1&amp;hl=en_US&amp;rel=0" }
      %meta{ itemprop: "width", content: 640 }
      %meta{ itemprop: "height", content: 385 }
      %param{ name: "movie", value: "http://www.youtube.com/v/#{post.youtube_id}?fs=1&amp;hl=en_US&amp;rel=0" }
      %param{ name: "allowFullScreen", value: "true" }
      %param{ name: "allowscriptaccess", value: "always" }
      %embed{ src: "http://www.youtube.com/v/#{post.youtube_id}?fs=1&amp;hl=en_US&amp;rel=0", type: "application/x-shockwave-flash", allowcriptaccess: "always", allowfullscreen: "true", width: "640", height: "385" }
  - elsif post.youtube_id.present?
    %p= link_to "Watch the screencast", post
  ~ markdown post.body
  %footer
    - unless params[:action] == "show"
      %p= link_to pluralize(post.comments.count, 'comment'), post, title: "Comments on #{post.title}", itemprop: "discussionUrl"
    - unless post.tags.empty?
      %p
        This post was tagged with #{post.tags.map { |tag| link_to tag.name, tag_path(tag), title: "Writing tagged with #{tag.name}", itemprop: "keywords" }.to_sentence.html_safe }.
    %p
      Find more content by #{link_to "browsing by tags", tags_path, title: "Browse writing by tags"}.

app/views/posts/edit.html.haml
- @page_title = "Edit post"
%h1 Edit post
= render "form"

app/views/posts/index.html.haml
= render @posts
%p.pagination= will_paginate @posts, container: false, inner_window: 2, outer_window: 0

app/views/posts/new.html.haml
- @page_title = "New post"
%h1 New post
= render "form"